Parsing mentions using moera commons and not regexes
MoeraOrg/moera-node pull request #6
Opened 2020-08-31 19:28 UTC by eliduvid

2020-08-31 19:39 UTC, smelamud requested changes

2020-08-31 19:39 UTC, smelamud commented on src/main/java/org/moera/node/text/markdown/mention/internal/MentionsInlineParserExtension.java
>          if (isPossible) {
I just though that adding early return here would make the code even simpler.

2020-09-01 22:06 UTC, smelamud requested changes

2020-09-01 22:06 UTC, smelamud commented on src/test/java/org/moera/node/text/markdown/mention/MentionsTest.java
> +}
Newline.

2020-09-01 22:06 UTC, smelamud commented on src/main/java/org/moera/node/text/markdown/mention/internal/MentionsNodeRenderer.java
> +                } catch (NamingNotAvailableException|NullPointerException ignore) {
Catching `NullPointerException` is too radical. If you know that `options.namingCache` may be `null`, just check this.

2020-09-01 22:06 UTC, smelamud commented on src/main/java/org/moera/node/text/markdown/mention/MentionsExtension.java
> +    public MentionsExtension() {
Do you use the constructor anywhere? I see only calls to `create()`. Anyway, if you need it for tests only, package access would be enough.

2020-09-02 05:12 UTC, eliduvid commented on src/main/java/org/moera/node/text/markdown/mention/internal/MentionsInlineParserExtension.java
> +        if (!(startingIndex == 0)) {
🤦‍♂️

2020-09-02 20:18 UTC, merged